bookshop_bookshop_homepage:
    pattern:  /
    defaults: { _controller: BookshopBookshopBundle:Default:index }
category:
  pattern: category/{id}
  defaults: { _controller: BookshopBookshopBundle:Default:category}
  requirements:
        _method:  GET
        id: \d+
        
cart:
  pattern: cart
  defaults: { _controller: BookshopBookshopBundle:Cart:index}

profile:
  pattern: profile/min
  defaults: { _controller: BookshopBookshopBundle:Profile:showMinim}
  
dashboard_index:
  pattern: dashboard/
  defaults: { _controller: BookshopBookshopBundle:Dashboard:index}


dashboard_billing_address_show:
  pattern: dashboard/billingAddress
  defaults: { _controller: BookshopBookshopBundle:Dashboard:billingAddressShow}

dashboard_billing_addr_preedit:
  pattern: dashboard/billingAddress/preedit
  defaults: { _controller: BookshopBookshopBundle:Dashboard:billingAddressPreEdit}
  
dashboard_billing_addr_new_edit:
  pattern: dashboard/billingAddress/edit
  defaults: { _controller: BookshopBookshopBundle:Dashboard:billingAddressEdit}
  
dashboard_billing_addr_edit:
  pattern: dashboard/billingAddress/edit
  defaults: { _controller: BookshopBookshopBundle:Dashboard:billingAddressEdit}
  requirements:
    _method: POST
        