bookshop_bookshop_homepage:
    pattern: /
    defaults: { _controller: BookshopBookshopBundle:Default:index }
    
bookshop_bookhop_set_locale:
  pattern:  /locale/{locale}
  defaults: { _controller: BookshopBookshopBundle:Default:setLocale }
  requirements:
    _method:  GET
    locale:   en|ro
    
category:
  pattern: category/{id}
  defaults: { _controller: BookshopBookshopBundle:Category:show}
  requirements:
        _method: GET
        id: \d+
product:
  pattern: product/{id}
  defaults: { _controller: BookshopBookshopBundle:Product:product}
  requirements:
        _method: GET
        id: \d+
search:
  pattern: search/
  defaults: { _controller: BookshopBookshopBundle:Search:search}
  requirements:
    _method: GET

mycart:
  pattern: mycart
  defaults: { _controller: BookshopBookshopBundle:Cart:mycart}
        
cart:
  pattern: cart
  defaults: { _controller: BookshopBookshopBundle:Cart:index}

updatecart:
  pattern: updatecart/
  defaults: { _controller: BookshopBookshopBundle:Cart:updatecart}
  requirements:
    method: post
    

emtpycart:
  pattern: emptycart/{cartid}
  defaults: { _controller: BookshopBookshopBundle:Cart:emptycart}
  requirements:
        _method: GET
        id: \d+

deleteproduct:
  pattern: deleteproduct/{id}/{cartid}
  defaults: { _controller: BookshopBookshopBundle:Cart:deleteproduct}
  requirements:
    _method: GET
    id: \d+
    cartid: \d+

addproduct:
  pattern: addproduct/
  defaults: { _controller: BookshopBookshopBundle:Cart:addproduct}
  requirements:
        _method: post

checkout:
  pattern: checkout/index
  defaults: { _controller: BookshopBookshopBundle:Checkout:index}

billing:
  pattern: checkout/billing
  defaults: { _controller: BookshopBookshopBundle:Checkout:billing}
shipping:
  pattern: checkout/shipping
  defaults: { _controller: BookshopBookshopBundle:Checkout:shipping}
shipping_method:
  pattern: checkout/shipping_method
  defaults: { _controller: BookshopBookshopBundle:Checkout:shippingMethod}

profile:
  pattern: profile/min
  defaults: { _controller: BookshopBookshopBundle:Profile:showMinim}
  
dashboard_index:
  pattern: dashboard/
  defaults: { _controller: BookshopBookshopBundle:Dashboard:index}


dashboard_billing_address_show:
  pattern: dashboard/billingAddress
  defaults: { _controller: BookshopBookshopBundle:Dashboard:billingAddressShow}

dashboard_billing_addr_preedit:
  pattern: dashboard/billingAddress/preedit
  defaults: { _controller: BookshopBookshopBundle:Dashboard:billingAddressPreEdit}
  
dashboard_billing_addr_new_edit:
  pattern: dashboard/billingAddress/edit
  defaults: { _controller: BookshopBookshopBundle:Dashboard:billingAddressEdit}
  
dashboard_billing_addr_edit:
  pattern: dashboard/billingAddress/edit
  defaults: { _controller: BookshopBookshopBundle:Dashboard:billingAddressEdit}
  requirements:
    _method: POST
    
dashboard_shipping_addr_preedit:
  pattern: dashboard/shippingAddress/preedit
  defaults: { _controller: BookshopBookshopBundle:Dashboard:shippingAddressPreEdit}
  
dashboard_shipping_addr_new_edit:
  pattern: dashboard/shippingAddress/edit
  defaults: { _controller: BookshopBookshopBundle:Dashboard:shippingAddressEdit}
  
dashboard_shipping_addr_edit:
  pattern: dashboard/shippingAddress/edit
  defaults: { _controller: BookshopBookshopBundle:Dashboard:shippingAddressEdit}
  requirements:
    _method: POST
