parameters:
#    bookshop_bookshop.example.class: Bookshop\BookshopBundle\Example

services:
    acme_user.registration.form.type:
            class: Bookshop\BookshopBundle\Form\Type\RegistrationFormType
            arguments: [%fos_user.model.user.class%]
            tags:
                - { name: form.type, alias: bookshop_user_registration }
